title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
remote_theme: cinemataztic/jekyll-theme-rtd

# Theme settings:
site_author: Cinemataztic
repo_url: "https://github.com/cinemataztic/jekyll-theme-rtd"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
